# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_n', models.DateField()),
                ('time_n', models.TimeField()),
                ('mode_belajar', models.CharField(max_length=20)),
                ('sensor_id', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('recommend_temperature', models.TextField()),
                ('humidity', models.FloatField()),
                ('recommend_humidity', models.TextField()),
                ('light_intensity', models.IntegerField()),
                ('recommend_light', models.TextField()),
                ('sound_intensity', models.IntegerField()),
                ('recommend_sound', models.TextField()),
            ],
        ),
    ]
